// Auto-generated Audio Asset Map (run `npm run generate:audio` to refresh)
export const audioMap = {
  "Welcome to Real-Life Ratio Problems! Ready to mix, share and scale like a pro? Let's roll!": "/assets/audio/home_intro.mp3",
  "key:home_intro": "/assets/audio/home_intro.mp3",
  "Robo makes a mango shake with 1 scoop of mango and 2 scoops of milk. Alex says: \"If you use 2 scoops of mango and 4 scoops of milk, the shake will taste stronger, because there is more mango!\" Is that actually true? Remember, same ratio means same taste. Multiply both parts by the same number and the ratio never changes!": "/assets/audio/wonder_prompt.mp3",
  "key:wonder_prompt": "/assets/audio/wonder_prompt.mp3",
  "What if you added 2 more scoops of mango but no extra milk? Would the shake still taste the same?": "/assets/audio/wonder_teaser.mp3",
  "key:wonder_teaser": "/assets/audio/wonder_teaser.mp3",
  "A ratio compares two amounts of the same kind. In Robo's mango shake there are 2 scoops of mango and 3 scoops of milk, so mango to milk is 2 : 3. That is a part-to-part ratio. Compare mango to the whole shake and you get a part-to-whole ratio, 2 : 5. Careful, order matters: 2 : 3 is not the same as 3 : 2!": "/assets/audio/story_slide_1.mp3",
  "key:story_slide_1": "/assets/audio/story_slide_1.mp3",
  "Make a bigger batch by multiplying both parts by the same number. Double the shake and 2 : 3 becomes 4 : 6. Triple it and you get 6 : 9. These are equivalent ratios, and they all taste exactly the same! To simplify, divide both parts by the same number, so 12 : 18 becomes 2 : 3.": "/assets/audio/story_slide_2.mp3",
  "key:story_slide_2": "/assets/audio/story_slide_2.mp3",
  "Robo and Alex share 40 stickers in the ratio 3 : 5. Draw a bar model: Robo gets 3 units and Alex gets 5 units, which is 8 units in total. Divide 40 by 8 to find that 1 unit is 5 stickers. So Robo gets 15 stickers and Alex gets 25!": "/assets/audio/story_slide_3.mp3",
  "key:story_slide_3": "/assets/audio/story_slide_3.mp3",
  "Detective time! Oats to raisins in a cookie mix is 4 : 3, and there are 20 g of oats. Four units are 20 g, so 1 unit is 5 g. Raisins are 3 units, so 3 × 5 = 15 g of raisins!": "/assets/audio/story_slide_4.mp3",
  "key:story_slide_4": "/assets/audio/story_slide_4.mp3",
  "Welcome to the Mango Shake Mixer! Add scoops of mango and milk to match the target shade. Use a different amount, because same ratio means same taste!": "/assets/audio/station_a_intro.mp3",
  "key:station_a_intro": "/assets/audio/station_a_intro.mp3",
  "Station B: Bar Model Builder! Build the bars to match the ratio, then find the value of 1 unit to share the total.": "/assets/audio/station_b_intro.mp3",
  "key:station_b_intro": "/assets/audio/station_b_intro.mp3",
  "Station C: Recipe Detective! One ingredient was scaled up the wrong way. Tap it, then fix the amount!": "/assets/audio/station_c_intro.mp3",
  "key:station_c_intro": "/assets/audio/station_c_intro.mp3",
  "Station D: Real-World Ratio Lab! Scale bubble tea, maps, rice and teams. Pick a multiplier to reach each mission goal!": "/assets/audio/station_d_intro.mp3",
  "key:station_d_intro": "/assets/audio/station_d_intro.mp3",
  "Choose your world on the map! Beat each world to unlock the next. Earn stars and XP!": "/assets/audio/practice_welcome.mp3",
  "key:practice_welcome": "/assets/audio/practice_welcome.mp3",
  "Awesome job! You got it right!": "/assets/audio/correct_cheer.mp3",
  "key:correct_cheer": "/assets/audio/correct_cheer.mp3",
  "Not quite. Check both parts of the ratio and try again!": "/assets/audio/incorrect_try_again.mp3",
  "key:incorrect_try_again": "/assets/audio/incorrect_try_again.mp3",
  "Oh no! Out of hearts! Don't worry, try again to master this world!": "/assets/audio/out_of_hearts.mp3",
  "key:out_of_hearts": "/assets/audio/out_of_hearts.mp3",
  "Congratulations! You completed the world and earned new stars!": "/assets/audio/world_complete.mp3",
  "key:world_complete": "/assets/audio/world_complete.mp3",
  "Your Performance! Amazing work! Let's reflect on what you learned.": "/assets/audio/reflect_intro.mp3",
  "key:reflect_intro": "/assets/audio/reflect_intro.mp3",
  "What does a ratio tell us?": "/assets/audio/reflect_q1.mp3",
  "key:reflect_q1": "/assets/audio/reflect_q1.mp3",
  "A ratio compares two amounts of the same kind, like 2 scoops of mango to 3 scoops of milk. The order matters!": "/assets/audio/reflect_a1.mp3",
  "key:reflect_a1": "/assets/audio/reflect_a1.mp3",
  "How do you write a ratio in simplest form?": "/assets/audio/reflect_q2.mp3",
  "key:reflect_q2": "/assets/audio/reflect_q2.mp3",
  "Divide both parts by the same number until nothing more divides both. For example, 12 : 18 becomes 2 : 3.": "/assets/audio/reflect_a2.mp3",
  "key:reflect_a2": "/assets/audio/reflect_a2.mp3",
  "How do you find an equivalent ratio?": "/assets/audio/reflect_q3.mp3",
  "key:reflect_q3": "/assets/audio/reflect_q3.mp3",
  "Multiply or divide both parts by the same number. So 2 : 3 is the same as 4 : 6 and 6 : 9.": "/assets/audio/reflect_a3.mp3",
  "key:reflect_a3": "/assets/audio/reflect_a3.mp3",
  "How do you share an amount in a given ratio?": "/assets/audio/reflect_q4.mp3",
  "key:reflect_q4": "/assets/audio/reflect_q4.mp3",
  "Add the parts to get the total units, divide the amount by the total units to find 1 unit, then multiply by each part!": "/assets/audio/reflect_a4.mp3",
  "key:reflect_a4": "/assets/audio/reflect_a4.mp3",
  "What do you do when only one amount is known?": "/assets/audio/reflect_q5.mp3",
  "key:reflect_q5": "/assets/audio/reflect_q5.mp3",
  "Match the known amount to its units, divide to find 1 unit, then multiply to find the other amount!": "/assets/audio/reflect_a5.mp3",
  "key:reflect_a5": "/assets/audio/reflect_a5.mp3",
  "Where do you see ratios in real life?": "/assets/audio/reflect_q6.mp3",
  "key:reflect_q6": "/assets/audio/reflect_q6.mp3",
  "In recipes, map scales, paint mixes, sharing money, model trains, and even bubble tea!": "/assets/audio/reflect_a6.mp3",
  "key:reflect_a6": "/assets/audio/reflect_a6.mp3",
  "A bag has 3 red marbles and 5 blue marbles. What is the ratio of red marbles to blue marbles?": "/assets/audio/w1_q1_prompt.mp3",
  "Say the amounts in the order they are asked: red first, then blue.": "/assets/audio/w1_q1_hint.mp3",
  "A fruit bowl has 4 apples and 7 oranges. What is the ratio of oranges to apples?": "/assets/audio/w1_q2_prompt.mp3",
  "Watch the order! The question names oranges first, so its number goes first.": "/assets/audio/w1_q2_hint.mp3",
  "Mei Ling has 6 pens and 5 pencils. What is the ratio of pencils to pens?": "/assets/audio/w1_q3_prompt.mp3",
  "Watch the order! The question names pencils first, so its number goes first.": "/assets/audio/w1_q3_hint.mp3",
  "A kueh box has 2 pink kuehs and 9 green kuehs. What is the ratio of pink kuehs to green kuehs?": "/assets/audio/w1_q4_prompt.mp3",
  "Say the amounts in the order they are asked: pink first, then green.": "/assets/audio/w1_q4_hint.mp3",
  "A box has 3 red and 4 green counters. What is the ratio of red counters to ALL the counters?": "/assets/audio/w1_q5_prompt.mp3",
  "Part to whole: the second number is the total. First find 3 + 4.": "/assets/audio/w1_q5_hint.mp3",
  "A shelter has 5 cats and 8 dogs. What is the ratio of dogs to cats?": "/assets/audio/w1_q6_prompt.mp3",
  "Watch the order! The question names dogs first, so its number goes first.": "/assets/audio/w1_q6_hint.mp3",
  "Ali cycled 5 km and walked 3 km. What is the ratio of the distance walked to the distance cycled?": "/assets/audio/w1_q7_prompt.mp3",
  "Watch the order! The question names walked first, so its number goes first.": "/assets/audio/w1_q7_hint.mp3",
  "A class has 7 boys and 6 girls. What is the ratio of girls to all the students?": "/assets/audio/w1_q8_prompt.mp3",
  "Part to whole: the second number is the total. First find 7 + 6.": "/assets/audio/w1_q8_hint.mp3",
  "A recipe uses 2 cups of flour and 3 cups of milk. What is the ratio of milk to flour?": "/assets/audio/w1_q9_prompt.mp3",
  "Watch the order! The question names milk first, so its number goes first.": "/assets/audio/w1_q9_hint.mp3",
  "A bus has 8 adults and 3 children. What is the ratio of children to adults?": "/assets/audio/w1_q10_prompt.mp3",
  "Watch the order! The question names children first, so its number goes first.": "/assets/audio/w1_q10_hint.mp3",
  "The ratio of boys to girls in a class is 12 : 18. Write the ratio in simplest form.": "/assets/audio/w2_q1_prompt.mp3",
  "Find the biggest number that divides both 12 and 18, then divide both parts by it.": "/assets/audio/w2_q1_hint.mp3",
  "Ali has 15 blue tiles and 20 white tiles. Write blue : white in simplest form.": "/assets/audio/w2_q2_prompt.mp3",
  "Find the biggest number that divides both 15 and 20, then divide both parts by it.": "/assets/audio/w2_q2_hint.mp3",
  "A ribbon is cut into two pieces, 10 cm and 25 cm. Write short : long in simplest form.": "/assets/audio/w2_q3_prompt.mp3",
  "Find the biggest number that divides both 10 and 25, then divide both parts by it.": "/assets/audio/w2_q3_hint.mp3",
  "A tank holds 28 litres of water and 16 litres of juice. Write water : juice in simplest form.": "/assets/audio/w2_q4_prompt.mp3",
  "Find the biggest number that divides both 28 and 16, then divide both parts by it.": "/assets/audio/w2_q4_hint.mp3",
  "Mrs Tan spent $24 and saved $32. Write the ratio spent : saved in simplest form.": "/assets/audio/w2_q5_prompt.mp3",
  "Find the biggest number that divides both 24 and 32, then divide both parts by it.": "/assets/audio/w2_q5_hint.mp3",
  "A choir has 36 girls and 24 boys. Write the ratio of girls to boys in simplest form.": "/assets/audio/w2_q6_prompt.mp3",
  "Find the biggest number that divides both 36 and 24, then divide both parts by it.": "/assets/audio/w2_q6_hint.mp3",
  "A paint mix has 18 ml of red and 30 ml of white. Write red : white in simplest form.": "/assets/audio/w2_q7_prompt.mp3",
  "Find the biggest number that divides both 18 and 30, then divide both parts by it.": "/assets/audio/w2_q7_hint.mp3",
  "A stall sold 45 chicken rice and 20 fish rice. Write chicken rice : fish rice in simplest form.": "/assets/audio/w2_q8_prompt.mp3",
  "Find the biggest number that divides both 45 and 20, then divide both parts by it.": "/assets/audio/w2_q8_hint.mp3",
  "A model train is 16 cm long and its track is 40 cm long. Write train : track in simplest form.": "/assets/audio/w2_q9_prompt.mp3",
  "Find the biggest number that divides both 16 and 40, then divide both parts by it.": "/assets/audio/w2_q9_hint.mp3",
  "A garden has 35 roses and 49 tulips. Write the ratio of roses to tulips in simplest form.": "/assets/audio/w2_q10_prompt.mp3",
  "Find the biggest number that divides both 35 and 49, then divide both parts by it.": "/assets/audio/w2_q10_hint.mp3",
  "Complete the equivalent ratio: 2 : 3 = 8 : ?": "/assets/audio/w3_q1_prompt.mp3",
  "Look at the first parts: 2 → 8. What did you multiply by? Do the same to 3.": "/assets/audio/w3_q1_hint.mp3",
  "Which number completes the equivalent ratio? 3 : 5 = 12 : ?": "/assets/audio/w3_q2_prompt.mp3",
  "Look at the first parts: 3 → 12. What did you multiply by? Do the same to 5.": "/assets/audio/w3_q2_hint.mp3",
  "Find the missing number in the equivalent ratio: 4 : 7 = ? : 21": "/assets/audio/w3_q3_prompt.mp3",
  "Look at the second parts: 7 → 21. What did you multiply by? Do the same to 4.": "/assets/audio/w3_q3_hint.mp3",
  "Complete the equivalent ratio: 5 : 2 = 35 : ?": "/assets/audio/w3_q4_prompt.mp3",
  "Look at the first parts: 5 → 35. What did you multiply by? Do the same to 2.": "/assets/audio/w3_q4_hint.mp3",
  "Which number completes the equivalent ratio? 3 : 8 = ? : 40": "/assets/audio/w3_q5_prompt.mp3",
  "Look at the second parts: 8 → 40. What did you multiply by? Do the same to 3.": "/assets/audio/w3_q5_hint.mp3",
  "Find the missing number in the equivalent ratio: 24 : 40 = 3 : ?": "/assets/audio/w3_q6_prompt.mp3",
  "Look at the first parts: 24 → 3. What did you divide by? Do the same to 40.": "/assets/audio/w3_q6_hint.mp3",
  "Complete the equivalent ratio: 18 : 27 = ? : 3": "/assets/audio/w3_q7_prompt.mp3",
  "Look at the second parts: 27 → 3. What did you divide by? Do the same to 18.": "/assets/audio/w3_q7_hint.mp3",
  "Which number completes the equivalent ratio? 6 : 7 = 30 : ?": "/assets/audio/w3_q8_prompt.mp3",
  "Look at the first parts: 6 → 30. What did you multiply by? Do the same to 7.": "/assets/audio/w3_q8_hint.mp3",
  "Find the missing number in the equivalent ratio: 9 : 4 = 63 : ?": "/assets/audio/w3_q9_prompt.mp3",
  "Look at the first parts: 9 → 63. What did you multiply by? Do the same to 4.": "/assets/audio/w3_q9_hint.mp3",
  "Complete the equivalent ratio: 20 : 15 = ? : 3": "/assets/audio/w3_q10_prompt.mp3",
  "Look at the second parts: 15 → 3. What did you divide by? Do the same to 20.": "/assets/audio/w3_q10_hint.mp3",
  "The ratio of boys to girls is 3 : 5. What is the ratio of boys to all the children?": "/assets/audio/w4_q1_prompt.mp3",
  "Add the parts to find the whole: 3 + 5 units. Boys are 3 of those units.": "/assets/audio/w4_q1_hint.mp3",
  "The ratio of cats to dogs is 2 : 3. What is the ratio of dogs to all the pets?": "/assets/audio/w4_q2_prompt.mp3",
  "Whole = cats + dogs. Dogs are 3 of the units in the whole.": "/assets/audio/w4_q2_hint.mp3",
  "The ratio of red to blue beads is 4 : 7. What is the ratio of blue beads to all the beads?": "/assets/audio/w4_q3_prompt.mp3",
  "Find the whole first: 4 + 7. Then put blue's 7 units over the whole.": "/assets/audio/w4_q3_hint.mp3",
  "In a fruit basket the ratio of apples to pears is 5 : 1. What is the ratio of apples to all the fruit?": "/assets/audio/w4_q4_prompt.mp3",
  "Whole = 5 + 1. Apples take up 5 of those units.": "/assets/audio/w4_q4_hint.mp3",
  "Pets are only cats and dogs. The ratio of cats to all pets is 2 : 7. What is the ratio of cats to dogs?": "/assets/audio/w4_q5_prompt.mp3",
  "Dogs = whole − cats. Take 2 units away from 7 units.": "/assets/audio/w4_q5_hint.mp3",
  "A pack has only red and green cards. The ratio of green to all cards is 3 : 8. What is red : green?": "/assets/audio/w4_q6_prompt.mp3",
  "Red = whole − green = 8 − 3 units. Then write red first.": "/assets/audio/w4_q6_hint.mp3",
  "Only boys and girls are in a club. The ratio of girls to all members is 4 : 9. What is boys : girls?": "/assets/audio/w4_q7_prompt.mp3",
  "Boys = whole − girls = 9 − 4 units. Write boys first.": "/assets/audio/w4_q7_hint.mp3",
  "A drink is made of tea and milk. Tea is 3 out of every 5 parts. What is the ratio of tea to milk?": "/assets/audio/w4_q8_prompt.mp3",
  "Milk is the rest of the 5 parts. How many parts are left after tea?": "/assets/audio/w4_q8_hint.mp3",
  "Juice is 5 out of every 9 parts in a punch. The rest is water. What is the ratio of juice to water?": "/assets/audio/w4_q9_prompt.mp3",
  "Water is the rest of the 9 parts: 9 − 5.": "/assets/audio/w4_q9_hint.mp3",
  "The ratio of adults to children at a fair is 6 : 1. What is the ratio of children to all the people?": "/assets/audio/w4_q10_prompt.mp3",
  "Whole = 6 + 1. Children are just 1 unit of it.": "/assets/audio/w4_q10_hint.mp3",
  "Robo and Alex share 40 stickers in the ratio 3 : 5. How many stickers does Alex get?": "/assets/audio/w5_q1_prompt.mp3",
  "Add the parts: 3 + 5 = 8 units. Divide 40 by 8 to find 1 unit.": "/assets/audio/w5_q1_hint.mp3",
  "Mei and Lin share $36 in the ratio 1 : 2. How much money does Lin get?": "/assets/audio/w5_q2_prompt.mp3",
  "Add the parts: 1 + 2 = 3 units. Divide 36 by 3 to find 1 unit.": "/assets/audio/w5_q2_hint.mp3",
  "A baker packs 45 tarts into red and green boxes in the ratio 2 : 3. How many tarts are in the red boxes?": "/assets/audio/w5_q3_prompt.mp3",
  "Add the parts: 2 + 3 = 5 units. Divide 45 by 5 to find 1 unit.": "/assets/audio/w5_q3_hint.mp3",
  "Ravi and Sam share 60 sweets in the ratio 3 : 2. How many sweets does Sam get?": "/assets/audio/w5_q4_prompt.mp3",
  "Add the parts: 3 + 2 = 5 units. Divide 60 by 5 to find 1 unit.": "/assets/audio/w5_q4_hint.mp3",
  "54 pupils are split into Team Red and Team Blue in the ratio 4 : 5. How many pupils are in Team Blue?": "/assets/audio/w5_q5_prompt.mp3",
  "Add the parts: 4 + 5 = 9 units. Divide 54 by 9 to find 1 unit.": "/assets/audio/w5_q5_hint.mp3",
  "Mum gives $48 to Jia and Hao in the ratio 1 : 3. How much money does Jia get?": "/assets/audio/w5_q6_prompt.mp3",
  "Add the parts: 1 + 3 = 4 units. Divide 48 by 4 to find 1 unit.": "/assets/audio/w5_q6_hint.mp3",
  "A shop has 72 T-shirts in white and black in the ratio 5 : 7. How many T-shirts are black?": "/assets/audio/w5_q7_prompt.mp3",
  "Add the parts: 5 + 7 = 12 units. Divide 72 by 12 to find 1 unit.": "/assets/audio/w5_q7_hint.mp3",
  "Two friends share 56 kueh in the ratio 3 : 4. How many kueh does the bigger share get?": "/assets/audio/w5_q8_prompt.mp3",
  "Add the parts: 3 + 4 = 7 units. Divide 56 by 7 to find 1 unit.": "/assets/audio/w5_q8_hint.mp3",
  "A 63-litre tank holds juice and water in the ratio 2 : 7. How many litres of water are there?": "/assets/audio/w5_q9_prompt.mp3",
  "Add the parts: 2 + 7 = 9 units. Divide 63 by 9 to find 1 unit.": "/assets/audio/w5_q9_hint.mp3",
  "A $90 prize is shared by Anna and Ben in the ratio 4 : 5. How much does Anna get?": "/assets/audio/w5_q10_prompt.mp3",
  "Add the parts: 4 + 5 = 9 units. Divide 90 by 9 to find 1 unit.": "/assets/audio/w5_q10_hint.mp3",
  "The ratio of red to blue beads is 3 : 4. There are 12 red beads. How many blue beads are there?": "/assets/audio/w6_q1_prompt.mp3",
  "3 units = 12. Divide to find what 1 unit is worth.": "/assets/audio/w6_q1_hint.mp3",
  "The ratio of boys to girls is 2 : 5. There are 10 boys. How many girls are there?": "/assets/audio/w6_q2_prompt.mp3",
  "2 units = 10. Divide to find what 1 unit is worth.": "/assets/audio/w6_q2_hint.mp3",
  "Rice and water are mixed in the ratio 5 : 3. 20 cups of rice are used. How many cups of water are needed?": "/assets/audio/w6_q3_prompt.mp3",
  "5 units = 20. Divide to find what 1 unit is worth.": "/assets/audio/w6_q3_hint.mp3",
  "Mango and milk are in the ratio 4 : 7 in a shake. There is 28 ml of mango. How much milk is there?": "/assets/audio/w6_q4_prompt.mp3",
  "4 units = 28. Divide to find what 1 unit is worth.": "/assets/audio/w6_q4_hint.mp3",
  "The ratio of pens to pencils is 3 : 8. There are 15 pens. How many pencils are there?": "/assets/audio/w6_q5_prompt.mp3",
  "3 units = 15. Divide to find what 1 unit is worth.": "/assets/audio/w6_q5_hint.mp3",
  "A chocolate bar has dark and milk squares in the ratio 6 : 5. There are 30 dark squares. How many milk squares?": "/assets/audio/w6_q6_prompt.mp3",
  "6 units = 30. Divide to find what 1 unit is worth.": "/assets/audio/w6_q6_hint.mp3",
  "The ratio of Ken's stamps to Lee's stamps is 2 : 9. Ken has 8 stamps. How many stamps does Lee have?": "/assets/audio/w6_q7_prompt.mp3",
  "2 units = 8. Divide to find what 1 unit is worth.": "/assets/audio/w6_q7_hint.mp3",
  "The ratio of red to green apples is 3 : 5. There are 15 red apples. How many apples are there altogether?": "/assets/audio/w6_q8_prompt.mp3",
  "3 units = 15. Find 1 unit, then count all 8 units.": "/assets/audio/w6_q8_hint.mp3",
  "The ratio of cats to dogs is 7 : 2. There are 14 dogs. How many cats are there?": "/assets/audio/w6_q9_prompt.mp3",
  "2 units = 14. Divide to find what 1 unit is worth.": "/assets/audio/w6_q9_hint.mp3",
  "Tea and milk are mixed in the ratio 5 : 4. There is 24 ml of milk. How many ml of drink are there altogether?": "/assets/audio/w6_q10_prompt.mp3",
  "4 units = 24. Find 1 unit, then count all 9 units.": "/assets/audio/w6_q10_hint.mp3",
  "Ann and Bo have stickers in the ratio 5 : 3. Ann has 24 more than Bo. How many stickers does Ann have?": "/assets/audio/w7_q1_prompt.mp3",
  "The gap is 5 − 3 = 2 units, and that gap is worth 24. Find 1 unit first.": "/assets/audio/w7_q1_hint.mp3",
  "The ratio of Sam's to Tim's marbles is 7 : 4. Sam has 15 more marbles. How many marbles does Tim have?": "/assets/audio/w7_q2_prompt.mp3",
  "The gap is 7 − 4 = 3 units, and that gap is worth 15. Find 1 unit first.": "/assets/audio/w7_q2_hint.mp3",
  "The ratio of boys to girls is 3 : 2. There are 9 more boys than girls. How many children are there in all?": "/assets/audio/w7_q3_prompt.mp3",
  "The gap is 3 − 2 = 1 units, and that gap is worth 9. Find 1 unit first.": "/assets/audio/w7_q3_hint.mp3",
  "The ratio of Ella's to Fay's savings is 9 : 5. Ella has $20 more. How much money does Ella have?": "/assets/audio/w7_q4_prompt.mp3",
  "The gap is 9 − 5 = 4 units, and that gap is worth 20. Find 1 unit first.": "/assets/audio/w7_q4_hint.mp3",
  "The ratio of roses to tulips is 8 : 3. There are 25 more roses than tulips. How many tulips are there?": "/assets/audio/w7_q5_prompt.mp3",
  "The gap is 8 − 3 = 5 units, and that gap is worth 25. Find 1 unit first.": "/assets/audio/w7_q5_hint.mp3",
  "A rope is cut in the ratio 4 : 1. The long piece is 18 cm longer than the short one. How long was the rope in cm?": "/assets/audio/w7_q6_prompt.mp3",
  "The gap is 4 − 1 = 3 units, and that gap is worth 18. Find 1 unit first.": "/assets/audio/w7_q6_hint.mp3",
  "Big and small cups are in the ratio 5 : 2. There are 21 more big cups than small cups. How many big cups?": "/assets/audio/w7_q7_prompt.mp3",
  "The gap is 5 − 2 = 3 units, and that gap is worth 21. Find 1 unit first.": "/assets/audio/w7_q7_hint.mp3",
  "The ratio of Jan's to Kit's stickers is 7 : 5. Jan has 16 more stickers. How many stickers does Kit have?": "/assets/audio/w7_q8_prompt.mp3",
  "The gap is 7 − 5 = 2 units, and that gap is worth 16. Find 1 unit first.": "/assets/audio/w7_q8_hint.mp3",
  "Cars and bikes in a car park are in the ratio 6 : 1. There are 35 more cars than bikes. How many cars are there?": "/assets/audio/w7_q9_prompt.mp3",
  "The gap is 6 − 1 = 5 units, and that gap is worth 35. Find 1 unit first.": "/assets/audio/w7_q9_hint.mp3",
  "The ratio of Mia's money to Nick's is 9 : 4. Mia has $30 more than Nick. How much do they have together?": "/assets/audio/w7_q10_prompt.mp3",
  "The gap is 9 − 4 = 5 units, and that gap is worth 30. Find 1 unit first.": "/assets/audio/w7_q10_hint.mp3",
  "Share 60 stickers among three friends in the ratio 2 : 3 : 5. How many does the biggest share get?": "/assets/audio/w8_q1_prompt.mp3",
  "Add all three parts: 2 + 3 + 5 = 10 units. Divide 60 by 10 to get 1 unit.": "/assets/audio/w8_q1_hint.mp3",
  "Three tanks hold water in the ratio 1 : 2 : 3. Altogether they hold 72 litres. How many litres in the middle tank?": "/assets/audio/w8_q2_prompt.mp3",
  "Add all three parts: 1 + 2 + 3 = 6 units. Divide 72 by 6 to get 1 unit.": "/assets/audio/w8_q2_hint.mp3",
  "Ali, Ben and Cara share $90 in the ratio 2 : 3 : 4. How much money does Cara get?": "/assets/audio/w8_q3_prompt.mp3",
  "Add all three parts: 2 + 3 + 4 = 9 units. Divide 90 by 9 to get 1 unit.": "/assets/audio/w8_q3_hint.mp3",
  "A drink has juice, water and soda in the ratio 1 : 3 : 4. The drink is 48 ml. How much juice is in it?": "/assets/audio/w8_q4_prompt.mp3",
  "Add all three parts: 1 + 3 + 4 = 8 units. Divide 48 by 8 to get 1 unit.": "/assets/audio/w8_q4_hint.mp3",
  "Red, green and blue beads are in the ratio 2 : 3 : 4. There are 12 green beads. How many beads are there in all?": "/assets/audio/w8_q5_prompt.mp3",
  "3 units = 12. Find 1 unit, then count all 9 units.": "/assets/audio/w8_q5_hint.mp3",
  "Pens, pencils and erasers are in the ratio 3 : 4 : 5. There are 20 pencils. How many erasers are there?": "/assets/audio/w8_q6_prompt.mp3",
  "4 units = 20. Find 1 unit first.": "/assets/audio/w8_q6_hint.mp3",
  "A ribbon is cut in the ratio 2 : 3 : 6. The longest piece is 24 cm longer than the shortest. How long is the middle piece?": "/assets/audio/w8_q7_prompt.mp3",
  "Longest − shortest = 6 − 2 = 4 units, which is worth 24 cm.": "/assets/audio/w8_q7_hint.mp3",
  "Three ropes are in the ratio 1 : 3 : 5. The longest is 32 m longer than the shortest. How long is the middle rope?": "/assets/audio/w8_q8_prompt.mp3",
  "Longest − shortest = 5 − 1 = 4 units, which is worth 32 m.": "/assets/audio/w8_q8_hint.mp3",
  "A : B = 2 : 3 and B : C = 3 : 5. What is the ratio A : B : C?": "/assets/audio/w8_q9_prompt.mp3",
  "B is already 3 in both ratios, so line them up: A : B : C.": "/assets/audio/w8_q9_hint.mp3",
  "A : B = 3 : 4 and B : C = 2 : 5. What is the ratio A : B : C?": "/assets/audio/w8_q10_prompt.mp3",
  "Make B the same in both ratios first. B is 4 in one and 2 in the other.": "/assets/audio/w8_q10_hint.mp3",
  "A recipe for 4 people uses 300 g of flour. How much flour is needed for 10 people?": "/assets/audio/w9_q1_prompt.mp3",
  "Find the flour for 1 person first: 300 ÷ 4. Then multiply by 10.": "/assets/audio/w9_q1_hint.mp3",
  "On a map, 1 cm stands for 5 km. Two towns are 6 cm apart on the map. What is the real distance?": "/assets/audio/w9_q2_prompt.mp3",
  "Each 1 cm on the map is 5 km in real life. Multiply by 6.": "/assets/audio/w9_q2_hint.mp3",
  "On a map, 1 cm stands for 5 km. Two cities are 40 km apart. How far apart are they on the map?": "/assets/audio/w9_q3_prompt.mp3",
  "Going from real distance to the map, divide instead of multiply.": "/assets/audio/w9_q3_hint.mp3",
  "3 notebooks cost $9. How much do 8 notebooks cost?": "/assets/audio/w9_q4_prompt.mp3",
  "Find the cost of 1 notebook first: $9 ÷ 3.": "/assets/audio/w9_q4_hint.mp3",
  "A tap fills 12 litres of water in 3 minutes. How many litres does it fill in 7 minutes?": "/assets/audio/w9_q5_prompt.mp3",
  "Find the litres filled in 1 minute: 12 ÷ 3. Then multiply by 7.": "/assets/audio/w9_q5_hint.mp3",
  "Blue and white paint are mixed in the ratio 2 : 5. How many litres of blue paint are needed to make 35 litres of paint?": "/assets/audio/w9_q6_prompt.mp3",
  "Total units = 2 + 5 = 7. Divide 35 litres by 7 to get 1 unit.": "/assets/audio/w9_q6_hint.mp3",
  "A model train is built to the scale 1 : 50. The model is 30 cm long. How long is the real train, in metres?": "/assets/audio/w9_q7_prompt.mp3",
  "Real length = 30 × 50 cm. Then change centimetres into metres (÷ 100).": "/assets/audio/w9_q7_hint.mp3",
  "A bubble tea cup holds 400 ml. The ratio of tea to milk is 3 : 1. How much milk is in the cup?": "/assets/audio/w9_q8_prompt.mp3",
  "Total units = 3 + 1 = 4. Divide 400 ml by 4.": "/assets/audio/w9_q8_hint.mp3",
  "Pack A has 4 pens for $6. Pack B has 6 pens for $8. Which pack costs less for each pen?": "/assets/audio/w9_q9_prompt.mp3",
  "Work out the cost of 1 pen in each pack: price ÷ number of pens.": "/assets/audio/w9_q9_hint.mp3",
  "A car uses 6 litres of petrol for 90 km. How many litres are needed for 240 km?": "/assets/audio/w9_q10_prompt.mp3",
  "Find how far 1 litre goes: 90 ÷ 6. Then see how many litres 240 km needs.": "/assets/audio/w9_q10_hint.mp3",
  "Ali and Ben have stickers in the ratio 3 : 2. Ali gives 6 to Ben, then they have equal amounts. How many did Ali have at first?": "/assets/audio/w10_q1_prompt.mp3",
  "After giving 6: Ali's 3 units − 6 = Ben's 2 units + 6. The 1-unit gap equals 12.": "/assets/audio/w10_q1_hint.mp3",
  "The ratio of boys to girls is 5 : 3. After 8 more girls join, the numbers of boys and girls are equal. How many boys are there?": "/assets/audio/w10_q2_prompt.mp3",
  "Equal means 3 units + 8 = 5 units. So 2 units = 8.": "/assets/audio/w10_q2_hint.mp3",
  "The ratio of red to blue marbles is 2 : 3. After 12 more red marbles are added, red and blue are equal. How many blue marbles?": "/assets/audio/w10_q3_prompt.mp3",
  "Red 2 units + 12 = Blue 3 units. So 1 unit = 12.": "/assets/audio/w10_q3_hint.mp3",
  "Mei's savings to Lin's savings is 3 : 5. Lin spends $20, then they have equal amounts. How much did Lin have at first?": "/assets/audio/w10_q4_prompt.mp3",
  "Lin's 5 units − $20 = Mei's 3 units. So 2 units = $20.": "/assets/audio/w10_q4_hint.mp3",
  "Adults to children at a hawker centre is 3 : 7. There are 40 people. 8 adults leave. What is the new ratio in simplest form?": "/assets/audio/w10_q5_prompt.mp3",
  "Find 1 unit first (40 ÷ 10). Take 8 away from the adults, then simplify.": "/assets/audio/w10_q5_hint.mp3",
  "Pencils to erasers is 5 : 2 and there are 84 altogether. After 12 more erasers are added, what is the new ratio in simplest form?": "/assets/audio/w10_q6_prompt.mp3",
  "1 unit = 84 ÷ 7. Add 12 to the erasers, then simplify the new ratio.": "/assets/audio/w10_q6_hint.mp3",
  "Zara and Yan have cookies in the ratio 4 : 7. Yan gives 9 to Zara, then they are equal. How many cookies are there in total?": "/assets/audio/w10_q7_prompt.mp3",
  "The gap of 3 units is split between them: 3 units = 9 + 9 = 18.": "/assets/audio/w10_q7_hint.mp3",
  "Dad is 30 years older than his son. Their ages are in the ratio 7 : 2. How old is the son?": "/assets/audio/w10_q8_prompt.mp3",
  "The age gap is 7 − 2 = 5 units, and it equals 30 years.": "/assets/audio/w10_q8_hint.mp3",
  "The ratio of boys to girls is 3 : 4. After 8 girls leave, the numbers are equal. How many children were there at first?": "/assets/audio/w10_q9_prompt.mp3",
  "Girls 4 units − 8 = Boys 3 units. So 1 unit = 8.": "/assets/audio/w10_q9_hint.mp3",
  "Kim's money to Lee's is 4 : 3. After Kim gets $15 more, the ratio becomes 5 : 3. How much did Kim have at first?": "/assets/audio/w10_q10_prompt.mp3",
  "Lee's 3 units did not change. Kim went from 4 units to 5 units, so 1 unit = $15.": "/assets/audio/w10_q10_hint.mp3"
};
export default audioMap;
